version: "2"

services:
  front:
    restart: always
    image: nginx:latest
    ports:
      - '80:80'
    container_name: ws-front
    networks:
      - net
    volumes:
      - ./app/dist:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro

  backend:
    restart: always
    image: alpine
    container_name: ws-backend
    volumes:
      - ./app/ws:/ws
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net
    command: "./ws"

networks:
  net:
    driver: bridge