version: "2"

services:
  front:
    restart: always
    image: nginx:latest
    ports:
      - '11281:80'
    container_name: ws-front
    networks:
      - net
    volumes:
      - ./app/dist:/usr/share/nginx/html/
      - /etc/localtime:/etc/localtime:ro

  backend:
    restart: always
    image: alpine
    container_name: ws-backend
    volumes:
      - ./app/ws:/ws
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '11280:11280'
    networks:
      - net
    command: "./ws"

networks:
  net:
    driver: bridge